AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    58ae1b8e-9447-4bf7-9a53-8b1e2394b010:
      size:
        width: 60
        height: 60
      position:
        x: 450
        'y': 170
      z: 0
      embeds: []
    731b9c2c-3f66-4517-8f49-8ac39a2cb2a4:
      size:
        width: 60
        height: 60
      position:
        x: 278
        'y': 166.4499969482422
      z: 0
      embeds: []
Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref DeployBucket
        S3Key: !Join
          - '/'
          - - !Ref LambdaFunctionName
            - package.zip
      Runtime: python3.6
      MemorySize: 2048
      Timeout: 60
      Environment:
        Variables:
          deploy_bucket: !Ref DeployBucket
          git_email: !Ref GitEmail
          git_token: !Ref GitToken
          git_username: !Ref GitUsername
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 58ae1b8e-9447-4bf7-9a53-8b1e2394b010
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSLambdaExecute'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 731b9c2c-3f66-4517-8f49-8ac39a2cb2a4
Parameters:
  GitUsername:
    Description: GitHub username
    Type: String
  GitEmail:
    Description: GitHub email address
    Type: String
  GitToken:
    Description: GitHub auth token
    Type: String
    NoEcho: true
  DeployBucket:
    Description: name of S3 bucket for storing zipped deployment packages
    Type: String
  LambdaFunctionName:
    Description: name of this Lambda function
    Type: String
    Default: lambda-lambda-lambda
